name: publish to Maven Central - for Batch Framework

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        options:
          - "javaconfig"
          - "xmlconfig"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: 'macchinetta/macchinetta-batch-blank'
          ref: '2.6.1.RELEASE'

      - name: Set up Java and Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Setup Groovy
        uses: wtfjoke/setup-groovy@v3
        with:
          groovy-version: "5.0.4"

      - name: Remove .gitkeep
        run: rm -rf macchinetta-batch-blankproject/src/main/resources/META-INF/*

      - name: Copy config(Java Config)
        if: ${{ github.event.inputs.choice == 'javaconfig' }}
        run: cp -R config/javaconfig/config macchinetta-batch-blankproject/src/main/java/xxxxxx/yyyyyy/zzzzzz/projectName

      - name: Copy config for jobs(Java Config)
        if: ${{ github.event.inputs.choice == 'javaconfig' }}
        run: cp -R config/javaconfig/jobs macchinetta-batch-blankproject/src/main/java/xxxxxx/yyyyyy/zzzzzz/projectName

      - name: Copy config(XML Config)
        if: ${{ github.event.inputs.choice == 'xmlconfig' }}
        run: cp -R config/xmlconfig/spring macchinetta-batch-blankproject/src/main/resources/META-INF

      - name: Copy config for jobs(XML Config)
        if: ${{ github.event.inputs.choice == 'xmlconfig' }}
        run: cp -R config/xmlconfig/jobs macchinetta-batch-blankproject/src/main/resources/META-INF

      - name: Create archetype
        run: cd macchinetta-batch-blankproject; mvn clean archetype:create-from-project -DpackageName=xxxxxx.yyyyyy.zzzzzz.projectName; cd ..; groovy CreateArchetype.groovy ${{github.event.inputs.choice}}
