name: publish to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        repository: 'macchinetta/macchinetta-web-blank'
        ref: '1.11.1-SNAPSHOT'

    - name: Set up Java and Maven
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: "21"
        cache: maven
        server-id: central
        server-username: MAVEN_CENTRAL_USERNAME
        server-password: MAVEN_CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrage: GPG_PASSPHRASE


    - name: Build
      run: bash ./create-maven-archetype-javaconfig-jsp-noorm.sh install central

    - name: Deploy
      run: mvn deploy -f tmp/target/generated-sources/archetype/pom.xml
      env:
        MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}