name: publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        required: true
        options:
          - "./create-maven-archetype-javaconfig-jsp-mybatis3.sh"
          - "./create-maven-archetype-javaconfig-thymeleaf-mybatis3.sh"
          - "./create-maven-archetype-xmlconfig-jsp-mybatis3.sh"
          - "./create-maven-archetype-xmlconfig-thymeleaf-mybatis3.sh"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: 'macchinetta/macchinetta-web-multi-blank'
          ref: '1.11.1.RELEASE'

      - name: Set up Java and Maven
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Remove RF
        run: find . -name '*.sh' -type f | xargs sed -i -e s/\\\\r//g

      - name: Change shell
        run: find . -name '*.sh' -type f | xargs sed -i -e s/^sh/bash/g

      - name: Build
        run: bash ${{ github.event.inputs.choice }} install central
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Deploy
        run: mvn deploy -f tmp/target/generated-sources/archetype/pom.xml
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
